package com.kazumaproject.markdownhelperkeyboard.ime_service.state

sealed class InputTypeForIME{
    object None: InputTypeForIME()
    object Text: InputTypeForIME()
    object TextCapCharacters: InputTypeForIME()
    object TextCapWords: InputTypeForIME()
    object TextCapSentences: InputTypeForIME()
    object TextAutoCorrect: InputTypeForIME()
    object TextAutoComplete: InputTypeForIME()
    object TextMultiLine: InputTypeForIME()
    object TextImeMultiLine: InputTypeForIME()
    object TextNoSuggestion: InputTypeForIME()
    object TextUri: InputTypeForIME()
    object TextEmailAddress: InputTypeForIME()
    object TextEmailSubject: InputTypeForIME()
    object TextShortMessage: InputTypeForIME()
    object TextLongMessage: InputTypeForIME()
    object TextPersonName: InputTypeForIME()
    object TextPostalAddress: InputTypeForIME()
    object TextPassword: InputTypeForIME()
    object TextVisiblePassword: InputTypeForIME()
    object TextWebEditText: InputTypeForIME()
    object TextFilter: InputTypeForIME()
    object TextPhonetic: InputTypeForIME()
    object TextWebEmailAddress: InputTypeForIME()
    object TextWebPassword: InputTypeForIME()
    object TextWebSearchView: InputTypeForIME()

    object TextSearchView: InputTypeForIME()
    object TextEditTextInBookingTDBank: InputTypeForIME()
    object TextWebSearchViewFireFox: InputTypeForIME()
    object TextNotCursorUpdate: InputTypeForIME()
    object Number: InputTypeForIME()
    object NumberSigned: InputTypeForIME()
    object NumberDecimal: InputTypeForIME()
    object NumberPassword: InputTypeForIME()
    object Phone: InputTypeForIME()
    object Datetime: InputTypeForIME()
    object Date: InputTypeForIME()
    object Time: InputTypeForIME()
}
