package com.kazumaproject.markdownhelperkeyboard.ime_service.state

sealed class InputTypeForIME {
    data object None : InputTypeForIME()
    data object Text : InputTypeForIME()
    data object TextCapCharacters : InputTypeForIME()
    data object TextCapWords : InputTypeForIME()
    data object TextCapSentences : InputTypeForIME()
    data object TextAutoCorrect : InputTypeForIME()
    data object TextAutoComplete : InputTypeForIME()
    data object TextMultiLine : InputTypeForIME()

    data object TextNextLine : InputTypeForIME()

    data object TextDone : InputTypeForIME()
    data object TextImeMultiLine : InputTypeForIME()
    data object TextNoSuggestion : InputTypeForIME()
    data object TextUri : InputTypeForIME()
    data object TextEmailAddress : InputTypeForIME()
    data object TextEmailSubject : InputTypeForIME()
    data object TextShortMessage : InputTypeForIME()
    data object TextLongMessage : InputTypeForIME()
    data object TextPersonName : InputTypeForIME()
    data object TextPostalAddress : InputTypeForIME()
    data object TextPassword : InputTypeForIME()
    data object TextVisiblePassword : InputTypeForIME()
    data object TextWebEditText : InputTypeForIME()
    data object TextFilter : InputTypeForIME()
    data object TextPhonetic : InputTypeForIME()
    data object TextWebEmailAddress : InputTypeForIME()
    data object TextWebPassword : InputTypeForIME()
    data object TextWebSearchView : InputTypeForIME()

    data object TextSearchView : InputTypeForIME()
    data object TextEditTextInWebView : InputTypeForIME()
    data object TextWebSearchViewFireFox : InputTypeForIME()
    data object TextNotCursorUpdate : InputTypeForIME()
    data object Number : InputTypeForIME()
    data object NumberSigned : InputTypeForIME()
    data object NumberDecimal : InputTypeForIME()
    data object NumberPassword : InputTypeForIME()
    data object Phone : InputTypeForIME()
    data object Datetime : InputTypeForIME()
    data object Date : InputTypeForIME()
    data object Time : InputTypeForIME()
}
