plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.plugin.compose'
}
android {
    namespace 'com.kazumaproject.enterparity'
    compileSdk {
        version = release(37)
    }
    defaultConfig {
        applicationId 'com.kazumaproject.enterparity'
        minSdk 26
        targetSdk 37
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures { compose true }
}
dependencies {
    implementation 'androidx.activity:activity-compose:1.8.2'
    implementation 'androidx.compose.foundation:foundation:1.5.4'
    implementation 'androidx.compose.ui:ui:1.5.4'
}
