package com.kazumaproject.core.domain.physical_shift_key

import android.view.KeyEvent

object PhysicalShiftKeyCodeMap {
    val keymap = mapOf(
        KeyEvent.KEYCODE_A to 'A',
        KeyEvent.KEYCODE_B to 'B',
        KeyEvent.KEYCODE_C to 'C',
        KeyEvent.KEYCODE_D to 'D',
        KeyEvent.KEYCODE_E to 'E',
        KeyEvent.KEYCODE_F to 'F',
        KeyEvent.KEYCODE_G to 'G',
        KeyEvent.KEYCODE_H to 'H',
        KeyEvent.KEYCODE_I to 'I',
        KeyEvent.KEYCODE_J to 'J',
        KeyEvent.KEYCODE_K to 'K',
        KeyEvent.KEYCODE_L to 'L',
        KeyEvent.KEYCODE_M to 'M',
        KeyEvent.KEYCODE_N to 'N',
        KeyEvent.KEYCODE_O to 'O',
        KeyEvent.KEYCODE_P to 'P',
        KeyEvent.KEYCODE_Q to 'Q',
        KeyEvent.KEYCODE_R to 'R',
        KeyEvent.KEYCODE_S to 'S',
        KeyEvent.KEYCODE_T to 'T',
        KeyEvent.KEYCODE_U to 'U',
        KeyEvent.KEYCODE_V to 'V',
        KeyEvent.KEYCODE_W to 'W',
        KeyEvent.KEYCODE_X to 'X',
        KeyEvent.KEYCODE_Y to 'Y',
        KeyEvent.KEYCODE_Z to 'Z',
        KeyEvent.KEYCODE_1 to '！',
        KeyEvent.KEYCODE_2 to '＠',
        KeyEvent.KEYCODE_3 to '＃',
        KeyEvent.KEYCODE_4 to '＄',
        KeyEvent.KEYCODE_5 to '％',
        KeyEvent.KEYCODE_6 to '＾',
        KeyEvent.KEYCODE_7 to '＆',
        KeyEvent.KEYCODE_8 to '＊',
        KeyEvent.KEYCODE_9 to '（',
        KeyEvent.KEYCODE_0 to '）',
        KeyEvent.KEYCODE_MINUS to '＿',
        KeyEvent.KEYCODE_EQUALS to '＋',
        KeyEvent.KEYCODE_LEFT_BRACKET to '『',
        KeyEvent.KEYCODE_RIGHT_BRACKET to '』',
        KeyEvent.KEYCODE_BACKSLASH to '｜',
        KeyEvent.KEYCODE_SEMICOLON to '：',
        KeyEvent.KEYCODE_APOSTROPHE to '”',
        KeyEvent.KEYCODE_COMMA to '＜',
        KeyEvent.KEYCODE_PERIOD to '＞',
        KeyEvent.KEYCODE_SLASH to '？',
        KeyEvent.KEYCODE_GRAVE to '〜',
    )
}
