#!/usr/bin/env python3
"""Generate Kotlin category metadata from the pinned Unicode source.

The generated Kotlin is written to stdout so callers can review/apply it explicitly.
"""

from __future__ import annotations

import argparse
from pathlib import Path


EMOJI_GROUPS = {
    "Smileys & Emotion": "S",
    "People & Body": "P",
    "Animals & Nature": "N",
    "Food & Drink": "F",
    "Travel & Places": "T",
    "Activities": "A",
    "Objects": "O",
    "Symbols": "Y",
    "Flags": "L",
}

def parse_emoji_test(path: Path) -> tuple[str, list[str]]:
    version = "unknown"
    current_group: str | None = None
    rows: list[str] = []
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if line.startswith("# Version:"):
            version = line.split(":", 1)[1].strip()
        elif line.startswith("# group:"):
            current_group = line.split(":", 1)[1].strip()
        elif line and not line.startswith("#") and ";" in line:
            category_code = EMOJI_GROUPS.get(current_group or "")
            if category_code is None:
                continue
            code_points = line.split(";", 1)[0].strip()
            rows.append(f"{category_code}:{code_points}")
    return version, rows


def chunks(rows: list[str], max_chars: int = 48_000) -> list[str]:
    result: list[str] = []
    current: list[str] = []
    current_size = 0
    for row in rows:
        row_size = len(row) + 1
        if current and current_size + row_size > max_chars:
            result.append("\n".join(current))
            current = []
            current_size = 0
        current.append(row)
        current_size += row_size
    if current:
        result.append("\n".join(current))
    return result


def render_chunks(name: str, rows: list[str]) -> str:
    rendered = []
    for chunk in chunks(rows):
        rendered.append('        """\n' + chunk + '\n        """.trimIndent()')
    return f"    private val {name} = arrayOf(\n" + ",\n".join(rendered) + "\n    )"


def render_kotlin(emoji_version: str, emoji_rows: list[str]) -> str:
    emoji_chunks = render_chunks("emojiDataChunks", emoji_rows)
    return f'''// Generated by tools/emoji_metadata/generate_category_metadata.py. Do not edit manually.
// Unicode Emoji {emoji_version}: https://www.unicode.org/Public/{emoji_version}.0/emoji/emoji-test.txt
package com.kazumaproject.domain

import com.kazumaproject.data.emoji.EmojiCategory

internal object EmojiCategoryMetadata {{
    const val UNICODE_VERSION: String = "{emoji_version}"

    private data class EmojiMetadata(val category: EmojiCategory, val order: Int)

    private val emojiIndex: Map<String, EmojiMetadata> by lazy(LazyThreadSafetyMode.PUBLICATION) {{
        val result = HashMap<String, EmojiMetadata>({len(emoji_rows) * 2})
        var order = 0
        emojiDataChunks.forEach {{ chunk ->
            chunk.lineSequence().filter(String::isNotBlank).forEach {{ line ->
                val separator = line.indexOf(':')
                val category = emojiCategory(line.substring(0, separator))
                val symbol = decodeCodePoints(line, separator + 1)
                result.putIfAbsent(symbol, EmojiMetadata(category, order))
                order++
            }}
        }}
        result
    }}

    // U+FE0E/U+FE0F select text/emoji presentation; they do not change the
    // Unicode/CLDR group. Some bundled entries add U+FE0F to characters whose
    // fully-qualified emoji-test sequence does not contain a selector.
    private val presentationIndependentEmojiIndex: Map<String, EmojiMetadata> by
        lazy(LazyThreadSafetyMode.PUBLICATION) {{
            val result = HashMap<String, EmojiMetadata>(emojiIndex.size * 2)
            emojiIndex.forEach {{ (symbol, metadata) ->
                val key = symbol.withoutPresentationSelectors()
                val existing = result[key]
                check(existing == null || existing.category == metadata.category) {{
                    "Presentation-independent emoji category collision for $key"
                }}
                if (existing == null || metadata.order < existing.order) {{
                    result[key] = metadata
                }}
            }}
            result
        }}

    fun emojiCategoryOf(symbol: String): EmojiCategory =
        emojiMetadataOf(symbol)?.category ?: EmojiCategory.UNKNOWN

    fun emojiOrderOf(symbol: String): Int = emojiMetadataOf(symbol)?.order ?: Int.MAX_VALUE

    internal fun emojiEntryCount(): Int = emojiIndex.size

    private fun emojiMetadataOf(symbol: String): EmojiMetadata? =
        emojiIndex[symbol]
            ?: presentationIndependentEmojiIndex[symbol.withoutPresentationSelectors()]

    private fun String.withoutPresentationSelectors(): String =
        replace("\uFE0E", "").replace("\uFE0F", "")

    private fun emojiCategory(code: String): EmojiCategory = when (code) {{
        "S" -> EmojiCategory.SMILEYS_EMOTION
        "P" -> EmojiCategory.PEOPLE_BODY
        "N" -> EmojiCategory.ANIMALS_NATURE
        "F" -> EmojiCategory.FOOD_DRINK
        "T" -> EmojiCategory.TRAVEL_PLACES
        "A" -> EmojiCategory.ACTIVITIES
        "O" -> EmojiCategory.OBJECTS
        "Y" -> EmojiCategory.SYMBOLS
        "L" -> EmojiCategory.FLAGS
        else -> error("Unknown emoji category code: $code")
    }}

    private fun decodeCodePoints(line: String, startIndex: Int): String {{
        val result = StringBuilder()
        var tokenStart = startIndex
        var index = startIndex
        while (index <= line.length) {{
            if (index == line.length || line[index] == ' ') {{
                if (index > tokenStart) {{
                    result.appendCodePoint(line.substring(tokenStart, index).toInt(16))
                }}
                tokenStart = index + 1
            }}
            index++
        }}
        return result.toString()
    }}

{emoji_chunks}
}}
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--emoji-test", type=Path, required=True)
    args = parser.parse_args()

    emoji_version, emoji_rows = parse_emoji_test(args.emoji_test)
    print(render_kotlin(emoji_version, emoji_rows), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
